/**
 * @fileoverview Core API type definitions for the Synthetic ERP Data Generation Platform.
 *
 * This module defines the foundational TypeScript interfaces and types used for
 * typed API communication across all frontend services. Every API service file,
 * Zustand store, and page component depends on these types for type-safe HTTP
 * communication with the backend API Gateway (/api/v1/).
 *
 * These types ensure a consistent contract between the React frontend and the
 * Flask backend, matching the response envelope, error format, and pagination
 * structures produced by the API Gateway's middleware and route handlers.
 *
 * @module types/api
 * @version 1.0.0
 */

// ============================================================================
// HTTP Method Type
// ============================================================================

/**
 * Supported HTTP methods for REST API communication.
 *
 * Maps to the standard HTTP verbs used by the API Gateway endpoints
 * under the /api/v1/ URL-path versioning scheme (R-012).
 *
 * - `GET`    — Retrieve resources or resource collections
 * - `POST`   — Create new resources or trigger actions
 * - `PUT`    — Replace an existing resource entirely
 * - `PATCH`  — Partially update an existing resource
 * - `DELETE` — Remove an existing resource
 */
export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';

// ============================================================================
// Sort Direction Type
// ============================================================================

/**
 * Sort direction for ordered query results.
 *
 * Used in conjunction with {@link PaginationParams.sort_by} to control
 * the ordering of paginated result sets returned by list endpoints.
 *
 * - `asc`  — Ascending order (A→Z, oldest→newest, lowest→highest)
 * - `desc` — Descending order (Z→A, newest→oldest, highest→lowest)
 */
export type SortDirection = 'asc' | 'desc';

// ============================================================================
// API Response Envelope
// ============================================================================

/**
 * Standard API response envelope wrapping all successful REST responses.
 *
 * All API Gateway endpoints return responses conforming to this structure,
 * providing a consistent contract for the frontend to parse and handle.
 * The generic type parameter `T` represents the shape of the response payload,
 * enabling fully typed data access without runtime type assertions.
 *
 * @typeParam T - The type of the response data payload
 *
 * @example
 * ```typescript
 * // Typed response for a single generation job
 * const response: ApiResponse<GenerationJob> = await api.get('/api/v1/generation/jobs/123');
 * if (response.success) {
 *   console.log(response.data.job_id);
 * }
 *
 * // Typed response wrapping a paginated result
 * const listResponse: ApiResponse<PaginatedResult<GenerationJob>> =
 *   await api.get('/api/v1/generation/jobs');
 * console.log(listResponse.data.items.length);
 * ```
 */
export interface ApiResponse<T> {
  /** Whether the API request completed successfully */
  success: boolean;

  /** The response payload, typed according to the generic parameter T */
  data: T;

  /** Optional human-readable message providing additional context about the response */
  message?: string | null;

  /** ISO 8601 timestamp indicating when the response was generated by the server */
  timestamp: string;
}

// ============================================================================
// Paginated Results
// ============================================================================

/**
 * Generic paginated result set for list endpoints.
 *
 * Wraps arrays of items with metadata for page-based pagination navigation.
 * Pages are 1-indexed (first page is page 1). The `total_pages` field is
 * computed server-side as `Math.ceil(total / page_size)`.
 *
 * Used by all list endpoints including generation jobs, schemas, profiles,
 * templates, audit logs, and user management resources.
 *
 * @typeParam T - The type of each item in the paginated result set
 *
 * @example
 * ```typescript
 * // Paginated list of generation jobs
 * const result: PaginatedResult<GenerationJob> = response.data;
 * console.log(`Showing page ${result.page} of ${result.total_pages}`);
 * console.log(`${result.items.length} items of ${result.total} total`);
 *
 * // Check for more pages
 * const hasNextPage = result.page < result.total_pages;
 * ```
 */
export interface PaginatedResult<T> {
  /** Array of result items for the current page */
  items: T[];

  /** Total number of items across all pages */
  total: number;

  /** Current page number (1-indexed, starting from 1) */
  page: number;

  /** Number of items per page */
  page_size: number;

  /** Total number of pages, computed as Math.ceil(total / page_size) */
  total_pages: number;
}

// ============================================================================
// API Error
// ============================================================================

/**
 * Structured error response matching the backend error_handler.py middleware.
 *
 * All API errors are returned in this format, enabling consistent error
 * handling and display across the frontend application. The `error_code`
 * field provides machine-readable codes for programmatic error handling,
 * while the `message` field contains human-readable descriptions for display.
 *
 * Supported HTTP status codes include:
 * - `400` — Bad Request (validation errors, malformed input)
 * - `401` — Unauthorized (authentication required or token expired)
 * - `403` — Forbidden (insufficient role/permissions per RBAC)
 * - `404` — Not Found (resource does not exist)
 * - `422` — Unprocessable Entity (semantic validation errors)
 * - `429` — Too Many Requests (rate limit exceeded per tier: 60/300/1000 req/min)
 * - `500` — Internal Server Error (unexpected server-side failure)
 * - `503` — Service Unavailable (circuit breaker open or dependency down)
 *
 * @example
 * ```typescript
 * try {
 *   await api.post('/api/v1/generation/jobs', jobConfig);
 * } catch (error) {
 *   const apiError: ApiError = error.response.data;
 *   console.error(`[${apiError.error_code}] ${apiError.message}`);
 *   if (apiError.request_id) {
 *     console.error(`Request ID: ${apiError.request_id}`);
 *   }
 * }
 * ```
 */
export interface ApiError {
  /** HTTP status code (e.g., 400, 401, 403, 404, 422, 429, 500, 503) */
  status_code: number;

  /**
   * Machine-readable error code for programmatic error handling.
   *
   * Examples: 'VALIDATION_ERROR', 'AUTHENTICATION_REQUIRED', 'FORBIDDEN',
   * 'RESOURCE_NOT_FOUND', 'RATE_LIMIT_EXCEEDED', 'INTERNAL_ERROR',
   * 'SERVICE_UNAVAILABLE', 'CIRCUIT_BREAKER_OPEN'
   */
  error_code: string;

  /** Human-readable error description suitable for display to end users */
  message: string;

  /**
   * Optional additional error context, such as field-level validation errors.
   *
   * For validation errors (422), this typically contains a mapping of field
   * names to their specific validation error messages. Uses `unknown` instead
   * of `any` for type safety.
   */
  details?: Record<string, unknown> | null;

  /** ISO 8601 timestamp indicating when the error occurred on the server */
  timestamp: string;

  /**
   * Optional OpenTelemetry correlation ID for distributed tracing.
   *
   * Enables support teams to trace individual requests across all
   * microservices in the platform for debugging and troubleshooting.
   */
  request_id?: string | null;
}

// ============================================================================
// Request Configuration
// ============================================================================

/**
 * Configuration options for customizing individual Axios HTTP requests.
 *
 * Extends the default Axios request behavior with typed query parameters,
 * custom headers, timeout overrides, abort signal support, and response
 * type selection. Used by all API service methods to pass additional
 * request-level configuration beyond the default client settings.
 *
 * @example
 * ```typescript
 * const config: RequestConfig = {
 *   params: { status: 'completed', page: 1 },
 *   headers: { 'X-Tenant-ID': 'tenant-123' },
 *   timeout: 30000,
 *   signal: abortController.signal,
 * };
 * const response = await generationApi.listJobs(config);
 *
 * // Download export as binary blob
 * const downloadConfig: RequestConfig = {
 *   responseType: 'blob',
 *   timeout: 120000,
 * };
 * const blob = await exportApi.downloadFile(jobId, downloadConfig);
 * ```
 */
export interface RequestConfig {
  /** URL query parameters as key-value pairs, automatically serialized by Axios */
  params?: Record<string, string | number | boolean | undefined>;

  /** Additional HTTP headers to include with the request */
  headers?: Record<string, string>;

  /** Request timeout in milliseconds, overriding the default Axios timeout */
  timeout?: number;

  /** AbortSignal for request cancellation via AbortController */
  signal?: AbortSignal;

  /**
   * Expected response data type.
   *
   * - `'json'`        — Parsed JSON object (default)
   * - `'blob'`        — Binary blob for file downloads (CSV, Parquet exports)
   * - `'arraybuffer'` — Raw ArrayBuffer for binary processing
   * - `'text'`        — Plain text response
   */
  responseType?: 'json' | 'blob' | 'arraybuffer' | 'text';
}

// ============================================================================
// Pagination Parameters
// ============================================================================

/**
 * Query parameters for requesting paginated data from list endpoints.
 *
 * Sent as URL query parameters on GET requests to endpoints that return
 * {@link PaginatedResult} responses. Pages are 1-indexed with a default
 * `page_size` of 20 and a maximum of 100, enforced by the API Gateway
 * rate limiting middleware.
 *
 * @example
 * ```typescript
 * const params: PaginationParams = {
 *   page: 1,
 *   page_size: 20,
 *   sort_by: 'created_at',
 *   sort_direction: 'desc',
 * };
 * const jobs = await generationApi.listJobs(params);
 * ```
 */
export interface PaginationParams {
  /** Page number to retrieve (1-indexed, defaults to 1) */
  page: number;

  /** Number of items per page (defaults to 20, maximum 100) */
  page_size: number;

  /**
   * Optional field name to sort results by.
   *
   * Common sort fields include 'created_at', 'updated_at', 'name',
   * 'status', and resource-specific fields documented per endpoint.
   */
  sort_by?: string;

  /** Sort direction, either ascending or descending */
  sort_direction?: SortDirection;
}

// ============================================================================
// Filter Parameters
// ============================================================================

/**
 * Common filter parameters for querying and narrowing list endpoint results.
 *
 * Provides standard filtering fields used across multiple API endpoints
 * including generation jobs, schemas, profiles, templates, and audit logs.
 * The index signature allows additional custom filter fields to be passed
 * without requiring interface extension, supporting endpoint-specific
 * filters beyond the common set.
 *
 * All date fields use ISO 8601 format (e.g., '2025-01-01T00:00:00Z').
 * The `tenant_id` field supports multi-tenant isolation (R-007) by
 * restricting results to a specific tenant namespace.
 *
 * @example
 * ```typescript
 * const filters: FilterParams = {
 *   search: 'financial',
 *   status: 'completed',
 *   tenant_id: 'tenant-abc',
 *   date_from: '2025-01-01T00:00:00Z',
 *   date_to: '2025-12-31T23:59:59Z',
 * };
 * const jobs = await generationApi.listJobs(paginationParams, filters);
 * ```
 */
export interface FilterParams {
  /** Free-text search query applied across relevant resource fields */
  search?: string;

  /**
   * Filter by resource status.
   *
   * Accepted values vary by endpoint (e.g., 'submitted', 'generating',
   * 'completed', 'failed' for generation jobs; 'pending', 'in_progress',
   * 'completed' for profiling operations).
   */
  status?: string;

  /** Filter by tenant namespace identifier for multi-tenant isolation */
  tenant_id?: string;

  /** Filter for resources created on or after this ISO 8601 date */
  date_from?: string;

  /** Filter for resources created on or before this ISO 8601 date */
  date_to?: string;

  /**
   * Index signature allowing additional custom filter parameters.
   *
   * Supports endpoint-specific filters beyond the common set defined above
   * (e.g., 'erp_type', 'method', 'module' for domain-specific queries).
   */
  [key: string]: string | number | boolean | undefined;
}
