"""CCPA (California Consumer Privacy Act) compliance rules and verification.

This module implements CCPA regulatory compliance verification for synthetic
datasets generated by the Synthetic ERP Data Generation Platform.  It checks
generated data against the personal information categories defined in
Cal. Civ. Code §1798.140(o), validates consumer rights compliance, and
enforces CPRA (California Privacy Rights Act) amendments for sensitive
personal information.

The :class:`CCPARegulationChecker` extends :class:`BaseRegulationChecker` and
is automatically registered in the :class:`RegulationRegistry` during package
import, enabling dynamic selection by the Compliance Service orchestration
layer.

Key compliance areas verified:

* **Personal Information Categories** — 9 categories per §1798.140(o)
* **Sensitive Personal Information** — CPRA §1798.140(ae)
* **Consumer Rights** — right to know, delete, opt-out, non-discrimination,
  correct, and limit use of sensitive PI
* **Data Sale Provisions** — §1798.120 opt-out and notice requirements
* **Minors Consent** — §1798.120(c)-(d) parental/opt-in requirements

Typical usage::

    from compliance_service.regulations.ccpa import CCPARegulationChecker

    checker = CCPARegulationChecker()
    result = checker.check_compliance(dataset_metadata, scan_results)
    if not result.is_compliant:
        for v in result.violations:
            print(f"[{v.severity.value}] {v.description}")
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional, Set

from shared.logging.structured_logger import get_logger

from compliance_service.regulations import (
    BaseRegulationChecker,
    ComplianceResult,
    ComplianceViolation,
    RegulationType,
    Severity,
)

# ---------------------------------------------------------------------------
# Module-level logger
# ---------------------------------------------------------------------------

_logger = get_logger(__name__)

# ---------------------------------------------------------------------------
# CCPA Personal Information Categories — Cal. Civ. Code §1798.140(o)
# ---------------------------------------------------------------------------

CCPA_PERSONAL_INFORMATION_CATEGORIES: Dict[str, List[str]] = {
    "identifiers": [
        "name",
        "first_name",
        "last_name",
        "alias",
        "postal_address",
        "street_address",
        "unique_personal_identifier",
        "online_identifier",
        "ip_address",
        "email",
        "email_address",
        "account_name",
        "ssn",
        "social_security_number",
        "drivers_license",
        "passport_number",
        "state_id",
    ],
    "commercial_information": [
        "purchase_history",
        "products_purchased",
        "services_purchased",
        "purchase_date",
        "order_history",
        "transaction_history",
        "shopping_cart",
        "payment_history",
    ],
    "biometric_information": [
        "fingerprint",
        "face_geometry",
        "voiceprint",
        "iris_scan",
        "retina_scan",
        "keystroke_patterns",
        "gait_patterns",
        "sleep_data",
        "health_data",
    ],
    "internet_activity": [
        "browsing_history",
        "search_history",
        "website_interactions",
        "app_interactions",
        "click_stream",
        "page_views",
        "session_data",
        "cookies",
    ],
    "geolocation_data": [
        "latitude",
        "longitude",
        "gps_coordinates",
        "location",
        "geo_location",
        "ip_geolocation",
        "cell_tower_data",
    ],
    "sensory_data": [
        "audio_recording",
        "video_recording",
        "photo",
        "thermal_data",
        "olfactory_data",
    ],
    "professional_information": [
        "employer",
        "job_title",
        "work_history",
        "professional_license",
        "salary",
        "performance_review",
    ],
    "education_information": [
        "school",
        "degree",
        "gpa",
        "enrollment_date",
        "student_id",
        "educational_record",
    ],
    "inferences": [
        "consumer_profile",
        "preferences",
        "characteristics",
        "psychological_trends",
        "predispositions",
        "behavior",
        "attitudes",
        "intelligence",
        "abilities",
        "aptitudes",
    ],
}

# ---------------------------------------------------------------------------
# CCPA Consumer Rights — §§1798.100 – 1798.125 (as amended by CPRA)
# ---------------------------------------------------------------------------

CCPA_CONSUMER_RIGHTS: Dict[str, str] = {
    "right_to_know": "Consumers can request disclosure of PI collected (§1798.100)",
    "right_to_delete": "Consumers can request deletion of PI (§1798.105)",
    "right_to_opt_out": "Consumers can opt out of sale of PI (§1798.120)",
    "right_to_non_discrimination": (
        "Consumers cannot be discriminated against for exercising rights (§1798.125)"
    ),
    "right_to_correct": (
        "Consumers can request correction of inaccurate PI — CPRA amendment (§1798.106)"
    ),
    "right_to_limit": (
        "Consumers can limit use of sensitive PI — CPRA amendment (§1798.121)"
    ),
}

# ---------------------------------------------------------------------------
# CPRA Sensitive Personal Information — Cal. Civ. Code §1798.140(ae)
# ---------------------------------------------------------------------------

_SENSITIVE_PI_FIELDS: Set[str] = {
    # Government-issued identifiers
    "ssn",
    "social_security_number",
    "drivers_license",
    "state_id",
    "passport_number",
    # Financial credentials
    "financial_account",
    "bank_account",
    "credit_card",
    "debit_card",
    "account_credentials",
    "account_password",
    # Precise geolocation
    "latitude",
    "longitude",
    "gps_coordinates",
    "precise_geolocation",
    # Racial / ethnic origin
    "racial_origin",
    "ethnic_origin",
    "race",
    "ethnicity",
    # Religious / philosophical beliefs
    "religion",
    "religious_beliefs",
    "philosophical_beliefs",
    # Trade-union membership
    "union_membership",
    "trade_union",
    # Personal communications content
    "message_content",
    "email_content",
    "mail_content",
    "sms_content",
    # Genetic / biometric / health
    "genetic_data",
    "dna",
    "genome",
    "fingerprint",
    "face_geometry",
    "voiceprint",
    "iris_scan",
    "retina_scan",
    "health_data",
    "medical_record",
    "diagnosis",
    "prescription",
    # Sex life / sexual orientation
    "sex_life",
    "sexual_orientation",
}

_SENSITIVE_PI_CATEGORIES: Set[str] = {
    "identifiers",
    "biometric_information",
    "geolocation_data",
}

# ---------------------------------------------------------------------------
# Pre-computed lookup sets for fast matching
# ---------------------------------------------------------------------------

_PI_CATEGORY_LOOKUP: Dict[str, Set[str]] = {
    category: {f.lower() for f in fields}
    for category, fields in CCPA_PERSONAL_INFORMATION_CATEGORIES.items()
}

_ALL_PI_FIELDS: Set[str] = set()
for _fields in _PI_CATEGORY_LOOKUP.values():
    _ALL_PI_FIELDS.update(_fields)


# ---------------------------------------------------------------------------
# Local helper dataclass for internal category match results
# ---------------------------------------------------------------------------


@dataclass
class _PIMatchResult:
    """Internal container for a personal-information category match.

    Attributes:
        category: CCPA PI category name (e.g. ``'identifiers'``).
        matched_field: The normalized field name that triggered the match.
        is_sensitive: Whether the match qualifies as sensitive PI under CPRA.
    """

    category: str
    matched_field: str
    is_sensitive: bool = field(default=False)


# ---------------------------------------------------------------------------
# Local enumeration for PI category types
# ---------------------------------------------------------------------------


class PICategoryType(Enum):
    """Classification of personal-information categories.

    Used internally to drive severity mapping during violation creation.
    """

    IDENTIFIER = "IDENTIFIER"
    BIOMETRIC = "BIOMETRIC"
    COMMERCIAL = "COMMERCIAL"
    INTERNET = "INTERNET"
    GEOLOCATION = "GEOLOCATION"
    SENSORY = "SENSORY"
    PROFESSIONAL = "PROFESSIONAL"
    EDUCATION = "EDUCATION"
    INFERENCE = "INFERENCE"


_CATEGORY_TO_TYPE: Dict[str, PICategoryType] = {
    "identifiers": PICategoryType.IDENTIFIER,
    "commercial_information": PICategoryType.COMMERCIAL,
    "biometric_information": PICategoryType.BIOMETRIC,
    "internet_activity": PICategoryType.INTERNET,
    "geolocation_data": PICategoryType.GEOLOCATION,
    "sensory_data": PICategoryType.SENSORY,
    "professional_information": PICategoryType.PROFESSIONAL,
    "education_information": PICategoryType.EDUCATION,
    "inferences": PICategoryType.INFERENCE,
}

_HIGH_SEVERITY_TYPES: Set[PICategoryType] = {
    PICategoryType.IDENTIFIER,
    PICategoryType.BIOMETRIC,
}


# ---------------------------------------------------------------------------
# Module-level helper functions
# ---------------------------------------------------------------------------


def _normalize_name(name: str) -> str:
    """Lowercase, strip whitespace, and replace hyphens/spaces with underscores.

    Args:
        name: Raw column or field name.

    Returns:
        Normalized string suitable for set-membership lookups.
    """
    return name.strip().lower().replace("-", "_").replace(" ", "_")


def _match_column_to_pi_category(
    column_name: str,
    column_type: str,
) -> Optional[str]:
    """Map a dataset column to a CCPA personal-information category.

    The lookup is performed against the pre-computed ``_PI_CATEGORY_LOOKUP``
    sets using the normalized column name.  If no exact match is found, a
    substring search is attempted against all registered PI field tokens.

    Args:
        column_name: The dataset column name.
        column_type: The declared data type of the column (e.g. ``'string'``).

    Returns:
        The CCPA PI category name (e.g. ``'identifiers'``) if matched,
        otherwise ``None``.
    """
    normalized = _normalize_name(column_name)

    # Exact match pass
    for category, field_set in _PI_CATEGORY_LOOKUP.items():
        if normalized in field_set:
            return category

    # Substring/contains pass — check if any PI field token is a substring
    # of the column name or vice-versa.
    for category, field_set in _PI_CATEGORY_LOOKUP.items():
        for pi_field in field_set:
            if pi_field in normalized or normalized in pi_field:
                return category

    # Type-hint heuristic: certain column types hint at PI regardless of name
    col_type_lower = column_type.lower() if column_type else ""
    type_category_map: Dict[str, str] = {
        "email": "identifiers",
        "ip_address": "identifiers",
        "ip": "identifiers",
        "ssn": "identifiers",
        "phone": "identifiers",
        "geolocation": "geolocation_data",
        "gps": "geolocation_data",
        "biometric": "biometric_information",
        "url": "internet_activity",
    }
    for type_hint, cat in type_category_map.items():
        if type_hint in col_type_lower:
            return cat

    return None


def _is_sensitive_pi(pi_category: str, column_name: str) -> bool:
    """Determine whether a PI match qualifies as *sensitive* under CPRA.

    Sensitive personal information is defined in Cal. Civ. Code §1798.140(ae)
    and includes government-issued IDs, financial credentials, precise
    geolocation, racial/ethnic origin, genetic data, biometric data, health
    data, sex-life/orientation, and contents of personal communications.

    Args:
        pi_category: The CCPA PI category (e.g. ``'identifiers'``).
        column_name: The original (non-normalized) column name.

    Returns:
        ``True`` if the field is classified as sensitive PI, ``False`` otherwise.
    """
    normalized = _normalize_name(column_name)

    # Direct field-level check
    if normalized in _SENSITIVE_PI_FIELDS:
        return True

    # Category-level check: certain entire categories are sensitive
    if pi_category in _SENSITIVE_PI_CATEGORIES:
        # For identifiers, only government IDs and SSN are sensitive —
        # not all identifiers qualify.
        if pi_category == "identifiers":
            gov_ids = {
                "ssn",
                "social_security_number",
                "drivers_license",
                "passport_number",
                "state_id",
            }
            return normalized in gov_ids
        return True

    # Substring heuristic for fields not in the exact set
    for sensitive_token in _SENSITIVE_PI_FIELDS:
        if sensitive_token in normalized or normalized in sensitive_token:
            return True

    return False


# ---------------------------------------------------------------------------
# CCPARegulationChecker
# ---------------------------------------------------------------------------


class CCPARegulationChecker(BaseRegulationChecker):
    """CCPA / CPRA regulation compliance checker.

    Validates synthetic datasets against the California Consumer Privacy Act
    (Cal. Civ. Code §1798.100-199.100) and its California Privacy Rights Act
    (CPRA) amendments.  The checker runs five independent verification passes:

    1. **Personal Information** — §1798.140(o) category detection.
    2. **Sensitive Personal Information** — §1798.140(ae) sensitive PI check.
    3. **Consumer Rights** — §§1798.100-125 rights compliance metadata.
    4. **Data Sale Provisions** — §1798.120 opt-out/notice requirements.
    5. **Minors Consent** — §1798.120(c)-(d) parental/opt-in consent.

    The checker aggregates all violations and delegates score calculation to
    the inherited :meth:`_calculate_compliance_score` helper.

    Attributes:
        regulation_type: Always ``RegulationType.CCPA``.
        logger: Structured logger bound to the module name.
        personal_info_patterns: Pre-computed lookup sets for PI categories.
        consumer_rights: Mapping of consumer-right identifiers to descriptions.
    """

    # ------------------------------------------------------------------
    # Abstract property implementation
    # ------------------------------------------------------------------

    @property
    def regulation_type(self) -> RegulationType:
        """Return the CCPA regulation type identifier."""
        return RegulationType.CCPA

    # ------------------------------------------------------------------
    # Initialization
    # ------------------------------------------------------------------

    def __init__(self) -> None:
        """Initialize the CCPA regulation checker.

        Pre-computes PI category lookup sets and binds a structured logger
        for compliance event reporting.
        """
        self.logger = get_logger(__name__)
        self.personal_info_patterns: Dict[str, Set[str]] = _PI_CATEGORY_LOOKUP
        self.consumer_rights: Dict[str, str] = CCPA_CONSUMER_RIGHTS

    # ------------------------------------------------------------------
    # Main compliance check
    # ------------------------------------------------------------------

    def check_compliance(
        self,
        dataset_metadata: Dict[str, Any],
        scan_results: Dict[str, Any],
    ) -> ComplianceResult:
        """Execute the full CCPA compliance check against a dataset.

        Runs all five sub-checks in sequence, collects all violations, and
        produces a single :class:`ComplianceResult`.

        Args:
            dataset_metadata: Dataset schema information, including:
                - ``columns`` (list[dict]): Column definitions with ``name``
                  and ``type`` keys.
                - ``generation_profile`` (dict): Generation configuration
                  with ``purpose``, ``consumer_rights_support``, etc.
                - ``data_sale`` (dict, optional): Sale/sharing metadata.
                - ``minors_data`` (dict, optional): Minors-related flags.
            scan_results: PII scan results from the PII detector, containing:
                - ``detected_entities`` (list[dict]): Entities with ``field``,
                  ``entity_type``, ``confidence``.
                - ``pii_fields`` (list[str]): Fields flagged as containing PII.
                - ``deidentified_fields`` (list[str]): Fields already
                  de-identified.

        Returns:
            A :class:`ComplianceResult` with ``is_compliant=True`` only when
            **all** sub-checks produce zero violations.
        """
        self.logger.info(
            "ccpa_compliance_check_started",
            regulation_type=RegulationType.CCPA.value,
            dataset_id=dataset_metadata.get("dataset_id", "unknown"),
        )

        columns: List[Dict[str, Any]] = dataset_metadata.get("columns", [])
        all_violations: List[ComplianceViolation] = []

        # 1. Personal Information categories — §1798.140(o)
        pi_violations = self.check_personal_information(columns, scan_results)
        all_violations.extend(pi_violations)

        # 2. Sensitive Personal Information — §1798.140(ae)
        spi_violations = self.check_sensitive_personal_information(
            columns, scan_results
        )
        all_violations.extend(spi_violations)

        # 3. Consumer Rights — §§1798.100-125
        rights_violations = self.check_consumer_rights(dataset_metadata)
        all_violations.extend(rights_violations)

        # 4. Data Sale Provisions — §1798.120
        sale_violations = self.check_data_sale_provisions(dataset_metadata)
        all_violations.extend(sale_violations)

        # 5. Minors Consent — §1798.120(c)-(d)
        minors_violations = self.check_minors_consent(dataset_metadata)
        all_violations.extend(minors_violations)

        # Determine overall compliance
        is_compliant = len(all_violations) == 0
        total_fields = len(columns)

        result = self._create_result(
            is_compliant=is_compliant,
            violations=all_violations,
            total_fields=total_fields,
            metadata={
                "pi_violations": len(pi_violations),
                "sensitive_pi_violations": len(spi_violations),
                "consumer_rights_violations": len(rights_violations),
                "data_sale_violations": len(sale_violations),
                "minors_consent_violations": len(minors_violations),
            },
        )

        self.logger.info(
            "ccpa_compliance_check_completed",
            regulation_type=RegulationType.CCPA.value,
            is_compliant=is_compliant,
            compliance_score=result.compliance_score,
            violation_count=len(all_violations),
            dataset_id=dataset_metadata.get("dataset_id", "unknown"),
        )

        return result

    # ------------------------------------------------------------------
    # Sub-check: Personal Information (§1798.140(o))
    # ------------------------------------------------------------------

    def check_personal_information(
        self,
        columns: List[Dict[str, Any]],
        scan_results: Dict[str, Any],
    ) -> List[ComplianceViolation]:
        """Check for CCPA personal-information categories in the dataset.

        Iterates through every column and the PII scan results, matching
        each field against the nine CCPA PI categories.  A violation is
        created for every field that contains (or is flagged as containing)
        personal information that has not been adequately de-identified.

        Args:
            columns: List of column dictionaries with at least ``name`` and
                ``type`` keys.
            scan_results: PII detector output containing
                ``detected_entities``, ``pii_fields``, and
                ``deidentified_fields``.

        Returns:
            List of :class:`ComplianceViolation` instances for every PI
            field detected.  Severity is ``HIGH`` for identifiers and
            biometric data, ``MEDIUM`` for other categories.
        """
        violations: List[ComplianceViolation] = []
        deidentified: Set[str] = {
            _normalize_name(f)
            for f in scan_results.get("deidentified_fields", [])
        }
        detected_entities: List[Dict[str, Any]] = scan_results.get(
            "detected_entities", []
        )

        # Build a fast lookup of fields flagged by the PII detector
        pii_field_set: Set[str] = {
            _normalize_name(f) for f in scan_results.get("pii_fields", [])
        }

        checked_fields: Set[str] = set()

        # --- Pass 1: column-level matching ---
        for col in columns:
            col_name = col.get("name", "")
            col_type = col.get("type", "")
            normalized = _normalize_name(col_name)

            if normalized in checked_fields:
                continue
            checked_fields.add(normalized)

            # Skip fields that have already been de-identified
            if normalized in deidentified:
                continue

            category = _match_column_to_pi_category(col_name, col_type)
            if category is None:
                continue

            # Determine severity based on category type
            cat_type = _CATEGORY_TO_TYPE.get(category, PICategoryType.INFERENCE)
            severity = (
                Severity.HIGH
                if cat_type in _HIGH_SEVERITY_TYPES
                else Severity.MEDIUM
            )

            violations.append(
                ComplianceViolation(
                    regulation_type=RegulationType.CCPA,
                    severity=severity,
                    article_reference="Cal. Civ. Code §1798.140(o)",
                    description=(
                        f"Column '{col_name}' matches CCPA personal information "
                        f"category '{category}' and has not been de-identified."
                    ),
                    affected_fields=[col_name],
                    remediation=(
                        f"De-identify or remove column '{col_name}' to comply "
                        f"with CCPA PI category '{category}'."
                    ),
                    metadata={"pi_category": category},
                )
            )

        # --- Pass 2: PII-detector entity matching ---
        for entity in detected_entities:
            entity_field = entity.get("field", "")
            entity_type = entity.get("entity_type", "")
            normalized = _normalize_name(entity_field)

            if normalized in checked_fields:
                continue
            checked_fields.add(normalized)

            if normalized in deidentified:
                continue

            category = _match_column_to_pi_category(entity_field, entity_type)
            if category is None and normalized in pii_field_set:
                # Default to identifiers when the PII detector flagged it
                # but we cannot determine a more specific category.
                category = "identifiers"

            if category is None:
                continue

            cat_type = _CATEGORY_TO_TYPE.get(category, PICategoryType.INFERENCE)
            severity = (
                Severity.HIGH
                if cat_type in _HIGH_SEVERITY_TYPES
                else Severity.MEDIUM
            )

            violations.append(
                ComplianceViolation(
                    regulation_type=RegulationType.CCPA,
                    severity=severity,
                    article_reference="Cal. Civ. Code §1798.140(o)",
                    description=(
                        f"PII detector flagged field '{entity_field}' "
                        f"(entity_type='{entity_type}') as matching CCPA "
                        f"personal information category '{category}'."
                    ),
                    affected_fields=[entity_field],
                    remediation=(
                        f"De-identify or remove field '{entity_field}' to "
                        f"comply with CCPA PI category '{category}'."
                    ),
                    metadata={
                        "pi_category": category,
                        "entity_type": entity_type,
                        "confidence": entity.get("confidence", 0.0),
                    },
                )
            )

        if violations:
            self.logger.warning(
                "ccpa_personal_information_detected",
                violation_count=len(violations),
                categories_affected=list(
                    {v.metadata.get("pi_category", "") for v in violations}
                ),
            )

        return violations

    # ------------------------------------------------------------------
    # Sub-check: Sensitive Personal Information (CPRA §1798.140(ae))
    # ------------------------------------------------------------------

    def check_sensitive_personal_information(
        self,
        columns: List[Dict[str, Any]],
        scan_results: Dict[str, Any],
    ) -> List[ComplianceViolation]:
        """Check for CPRA-defined sensitive personal information.

        Sensitive PI includes government-issued IDs (SSN, driver's license,
        passport), financial account credentials, precise geolocation,
        racial/ethnic origin, religious beliefs, union membership, contents
        of personal communications, genetic/biometric/health data, and
        sex-life/sexual-orientation data.

        Args:
            columns: List of column dictionaries with ``name`` and ``type``.
            scan_results: PII detector output.

        Returns:
            List of ``CRITICAL``-severity :class:`ComplianceViolation`
            instances for every sensitive PI field detected.
        """
        violations: List[ComplianceViolation] = []
        deidentified: Set[str] = {
            _normalize_name(f)
            for f in scan_results.get("deidentified_fields", [])
        }
        checked_fields: Set[str] = set()

        for col in columns:
            col_name = col.get("name", "")
            col_type = col.get("type", "")
            normalized = _normalize_name(col_name)

            if normalized in checked_fields:
                continue
            checked_fields.add(normalized)

            if normalized in deidentified:
                continue

            category = _match_column_to_pi_category(col_name, col_type)
            if category is None:
                continue

            if not _is_sensitive_pi(category, col_name):
                continue

            violations.append(
                ComplianceViolation(
                    regulation_type=RegulationType.CCPA,
                    severity=Severity.CRITICAL,
                    article_reference="Cal. Civ. Code §1798.140(ae)",
                    description=(
                        f"Column '{col_name}' contains CPRA-defined sensitive "
                        f"personal information (category='{category}')."
                    ),
                    affected_fields=[col_name],
                    remediation=(
                        f"Sensitive PI in column '{col_name}' must be removed "
                        f"or thoroughly de-identified. Consumers have the right "
                        f"to limit use of sensitive PI under §1798.121."
                    ),
                    metadata={
                        "pi_category": category,
                        "sensitive": True,
                    },
                )
            )

        # Also check PII detector entities for sensitive matches
        detected_entities: List[Dict[str, Any]] = scan_results.get(
            "detected_entities", []
        )
        for entity in detected_entities:
            entity_field = entity.get("field", "")
            entity_type = entity.get("entity_type", "")
            normalized = _normalize_name(entity_field)

            if normalized in checked_fields:
                continue
            checked_fields.add(normalized)

            if normalized in deidentified:
                continue

            category = _match_column_to_pi_category(entity_field, entity_type)
            if category is None:
                continue

            if not _is_sensitive_pi(category, entity_field):
                continue

            violations.append(
                ComplianceViolation(
                    regulation_type=RegulationType.CCPA,
                    severity=Severity.CRITICAL,
                    article_reference="Cal. Civ. Code §1798.140(ae)",
                    description=(
                        f"PII detector flagged field '{entity_field}' "
                        f"(entity_type='{entity_type}') as CPRA-defined "
                        f"sensitive personal information."
                    ),
                    affected_fields=[entity_field],
                    remediation=(
                        f"Remove or de-identify sensitive PI in '{entity_field}'. "
                        f"Consumers may limit use under §1798.121."
                    ),
                    metadata={
                        "pi_category": category,
                        "entity_type": entity_type,
                        "sensitive": True,
                        "confidence": entity.get("confidence", 0.0),
                    },
                )
            )

        if violations:
            self.logger.warning(
                "ccpa_sensitive_pi_detected",
                violation_count=len(violations),
                regulation_reference="Cal. Civ. Code §1798.140(ae)",
            )

        return violations

    # ------------------------------------------------------------------
    # Sub-check: Consumer Rights (§§1798.100-125)
    # ------------------------------------------------------------------

    def check_consumer_rights(
        self,
        dataset_metadata: Dict[str, Any],
    ) -> List[ComplianceViolation]:
        """Validate that the generation profile supports CCPA consumer rights.

        Each of the six consumer rights (right to know, delete, opt-out,
        non-discrimination, correct, limit) must be acknowledged and
        supported in the dataset's generation profile.  Missing support
        for any right creates a ``HIGH``-severity violation.

        Args:
            dataset_metadata: Must include a ``generation_profile`` dict
                with a ``consumer_rights_support`` mapping indicating which
                rights are supported (``True``/``False``).

        Returns:
            List of :class:`ComplianceViolation` for unsupported rights.
        """
        violations: List[ComplianceViolation] = []
        profile: Dict[str, Any] = dataset_metadata.get("generation_profile", {})
        rights_support: Dict[str, bool] = profile.get(
            "consumer_rights_support", {}
        )

        right_article_map: Dict[str, str] = {
            "right_to_know": "Cal. Civ. Code §1798.100",
            "right_to_delete": "Cal. Civ. Code §1798.105",
            "right_to_opt_out": "Cal. Civ. Code §1798.120",
            "right_to_non_discrimination": "Cal. Civ. Code §1798.125",
            "right_to_correct": "Cal. Civ. Code §1798.106",
            "right_to_limit": "Cal. Civ. Code §1798.121",
        }

        right_remediation_map: Dict[str, str] = {
            "right_to_know": (
                "Ensure the dataset supports disclosure queries so consumers "
                "can request what PI has been collected."
            ),
            "right_to_delete": (
                "Ensure the dataset and its derived artifacts can be fully "
                "deleted upon consumer request."
            ),
            "right_to_opt_out": (
                "Implement an opt-out mechanism allowing consumers to prevent "
                "sale or sharing of their PI."
            ),
            "right_to_non_discrimination": (
                "Remove any metadata that could enable discrimination against "
                "consumers exercising their privacy rights."
            ),
            "right_to_correct": (
                "Provide a correction mechanism allowing consumers to request "
                "updates to inaccurate PI (CPRA §1798.106)."
            ),
            "right_to_limit": (
                "Support limiting the use and disclosure of sensitive personal "
                "information upon consumer request (CPRA §1798.121)."
            ),
        }

        for right_key, right_desc in CCPA_CONSUMER_RIGHTS.items():
            is_supported = rights_support.get(right_key, False)
            if not is_supported:
                article = right_article_map.get(
                    right_key, "Cal. Civ. Code §1798.100-199.100"
                )
                remediation = right_remediation_map.get(
                    right_key,
                    f"Add support for '{right_key}' in the generation profile.",
                )
                violations.append(
                    ComplianceViolation(
                        regulation_type=RegulationType.CCPA,
                        severity=Severity.HIGH,
                        article_reference=article,
                        description=(
                            f"Consumer right '{right_key}' is not supported "
                            f"in the generation profile. {right_desc}"
                        ),
                        affected_fields=[],
                        remediation=remediation,
                        metadata={"consumer_right": right_key},
                    )
                )

        if violations:
            self.logger.warning(
                "ccpa_consumer_rights_violations",
                violation_count=len(violations),
                unsupported_rights=[
                    v.metadata.get("consumer_right", "") for v in violations
                ],
            )
        else:
            self.logger.info(
                "ccpa_consumer_rights_validated",
                supported_rights=list(CCPA_CONSUMER_RIGHTS.keys()),
            )

        return violations

    # ------------------------------------------------------------------
    # Sub-check: Data Sale Provisions (§1798.120)
    # ------------------------------------------------------------------

    def check_data_sale_provisions(
        self,
        dataset_metadata: Dict[str, Any],
    ) -> List[ComplianceViolation]:
        """Validate CCPA data-sale provisions if data is marked for sale/sharing.

        When the dataset metadata indicates that the generated synthetic data
        will be sold or shared with third parties, this check ensures all
        §1798.120 requirements are met: a "Do Not Sell or Share My Personal
        Information" opt-out link must be provided, and a notice-at-collection
        must be present.

        If the ``data_sale`` key is absent or ``is_sold`` is ``False``, the
        check is skipped (no violations).

        Args:
            dataset_metadata: Must include ``data_sale`` dict when applicable.

        Returns:
            List of ``HIGH``-severity :class:`ComplianceViolation` for
            unmet sale provisions.
        """
        violations: List[ComplianceViolation] = []
        data_sale: Dict[str, Any] = dataset_metadata.get("data_sale", {})

        # Only run when data is explicitly marked for sale/sharing
        is_sold = data_sale.get("is_sold", False)
        is_shared = data_sale.get("is_shared", False)

        if not (is_sold or is_shared):
            return violations

        # Check opt-out link
        opt_out_link_provided = data_sale.get("opt_out_link_provided", False)
        if not opt_out_link_provided:
            violations.append(
                ComplianceViolation(
                    regulation_type=RegulationType.CCPA,
                    severity=Severity.HIGH,
                    article_reference="Cal. Civ. Code §1798.120",
                    description=(
                        "Data is marked for sale/sharing but no 'Do Not Sell "
                        "or Share My Personal Information' opt-out link is "
                        "provided."
                    ),
                    affected_fields=[],
                    remediation=(
                        "Provide a clear and conspicuous opt-out link per "
                        "§1798.120 before selling or sharing consumer PI."
                    ),
                    metadata={"provision": "opt_out_link"},
                )
            )

        # Check notice at collection
        notice_at_collection = data_sale.get("notice_at_collection", False)
        if not notice_at_collection:
            violations.append(
                ComplianceViolation(
                    regulation_type=RegulationType.CCPA,
                    severity=Severity.HIGH,
                    article_reference="Cal. Civ. Code §1798.100(b)",
                    description=(
                        "Data is marked for sale/sharing but the required "
                        "notice at collection is missing."
                    ),
                    affected_fields=[],
                    remediation=(
                        "Provide a notice at or before the point of collection "
                        "informing consumers of the categories of PI to be "
                        "collected and the purposes per §1798.100(b)."
                    ),
                    metadata={"provision": "notice_at_collection"},
                )
            )

        # Check service provider agreement (CPRA requirement)
        service_provider_agreement = data_sale.get(
            "service_provider_agreement", False
        )
        if not service_provider_agreement:
            violations.append(
                ComplianceViolation(
                    regulation_type=RegulationType.CCPA,
                    severity=Severity.HIGH,
                    article_reference="Cal. Civ. Code §1798.140(ag)",
                    description=(
                        "Data is marked for sharing but no service provider "
                        "or contractor agreement is documented."
                    ),
                    affected_fields=[],
                    remediation=(
                        "Execute a service provider or contractor agreement "
                        "that restricts processing to the business purpose "
                        "per §1798.140(ag)."
                    ),
                    metadata={"provision": "service_provider_agreement"},
                )
            )

        if violations:
            self.logger.warning(
                "ccpa_data_sale_violations",
                violation_count=len(violations),
                is_sold=is_sold,
                is_shared=is_shared,
            )

        return violations

    # ------------------------------------------------------------------
    # Sub-check: Minors Consent (§1798.120(c)-(d))
    # ------------------------------------------------------------------

    def check_minors_consent(
        self,
        dataset_metadata: Dict[str, Any],
    ) -> List[ComplianceViolation]:
        """Validate consent mechanisms for data representing minors.

        If the dataset contains records representing individuals under 16,
        CCPA requires:

        * **Under 13** — affirmative parental or guardian consent.
        * **13–15** — the minor's own affirmative opt-in consent.

        If the ``minors_data`` metadata key is absent or
        ``contains_minors`` is ``False``, no checks are performed.

        Args:
            dataset_metadata: Must include ``minors_data`` dict when the
                dataset represents minors.

        Returns:
            List of ``CRITICAL``-severity :class:`ComplianceViolation`
            for inadequate consent mechanisms.
        """
        violations: List[ComplianceViolation] = []
        minors_data: Dict[str, Any] = dataset_metadata.get("minors_data", {})

        contains_minors = minors_data.get("contains_minors", False)
        if not contains_minors:
            return violations

        min_age = minors_data.get("minimum_age", None)
        parental_consent = minors_data.get("parental_consent_obtained", False)
        minor_opt_in = minors_data.get("minor_opt_in_obtained", False)

        # Children under 13: require parental consent
        if min_age is not None and min_age < 13 and not parental_consent:
            violations.append(
                ComplianceViolation(
                    regulation_type=RegulationType.CCPA,
                    severity=Severity.CRITICAL,
                    article_reference="Cal. Civ. Code §1798.120(c)",
                    description=(
                        "Dataset contains data representing children under 13 "
                        "but parental or guardian consent has not been obtained."
                    ),
                    affected_fields=[],
                    remediation=(
                        "Obtain verifiable parental consent before selling or "
                        "sharing personal information of children under 13 "
                        "per §1798.120(c)."
                    ),
                    metadata={
                        "minimum_age": min_age,
                        "consent_type": "parental",
                    },
                )
            )

        # Children 13-15: require opt-in consent from the minor
        if (
            min_age is not None
            and 13 <= min_age < 16
            and not minor_opt_in
        ):
            violations.append(
                ComplianceViolation(
                    regulation_type=RegulationType.CCPA,
                    severity=Severity.CRITICAL,
                    article_reference="Cal. Civ. Code §1798.120(d)",
                    description=(
                        "Dataset contains data representing minors aged 13-15 "
                        "but the minor's affirmative opt-in consent has not "
                        "been obtained."
                    ),
                    affected_fields=[],
                    remediation=(
                        "Obtain the minor's own opt-in consent before selling "
                        "or sharing their personal information per §1798.120(d)."
                    ),
                    metadata={
                        "minimum_age": min_age,
                        "consent_type": "minor_opt_in",
                    },
                )
            )

        # When contains_minors is True but no age info is provided, flag it
        if min_age is None:
            if not parental_consent and not minor_opt_in:
                violations.append(
                    ComplianceViolation(
                        regulation_type=RegulationType.CCPA,
                        severity=Severity.CRITICAL,
                        article_reference="Cal. Civ. Code §1798.120(c)-(d)",
                        description=(
                            "Dataset is marked as containing minors' data but "
                            "neither minimum age nor consent mechanisms are "
                            "documented."
                        ),
                        affected_fields=[],
                        remediation=(
                            "Document the minimum age of represented individuals "
                            "and obtain appropriate consent (parental for under "
                            "13, minor opt-in for 13-15) per §1798.120(c)-(d)."
                        ),
                        metadata={"consent_type": "unknown"},
                    )
                )

        if violations:
            self.logger.warning(
                "ccpa_minors_consent_violations",
                violation_count=len(violations),
                minimum_age=min_age,
                parental_consent=parental_consent,
                minor_opt_in=minor_opt_in,
            )
        else:
            self.logger.info(
                "ccpa_minors_consent_validated",
                minimum_age=min_age,
            )

        return violations

    # ------------------------------------------------------------------
    # Regulation identity
    # ------------------------------------------------------------------

    def get_regulation_name(self) -> str:
        """Return the full human-readable regulation name.

        Returns:
            ``'CCPA - California Consumer Privacy Act'``
        """
        return "CCPA - California Consumer Privacy Act"

    def get_regulation_version(self) -> str:
        """Return the legal citation for the regulation.

        Returns:
            ``'Cal. Civ. Code §1798.100-199.100 (as amended by CPRA)'``
        """
        return "Cal. Civ. Code §1798.100-199.100 (as amended by CPRA)"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

__all__ = [
    "CCPA_CONSUMER_RIGHTS",
    "CCPA_PERSONAL_INFORMATION_CATEGORIES",
    "CCPARegulationChecker",
]
